DROP TABLE IF EXISTS MANAGER.EMPLOYE;
DROP TABLE IF EXISTS MANAGER.DEPARTMENT;


CREATE TABLE MANAGER.EMPLOYE (
  ID_EMPLOYE bigint auto_increment  PRIMARY KEY NOT NULL,
  ID_DEPARTMENT BIGINT NOT NULL,  
  FULL_NAME VARCHAR(100) NOT NULL,
  POSITION VARCHAR(100) NOT NULL,
  SALARY DECIMAL(10,4) NOT NULL,
  FULL_TIME VARCHAR(15) NOT NULL
);

CREATE TABLE MANAGER.DEPARTMENT(
	ID_DEPARTMENT BIGINT PRIMARY KEY NOT NULL,
	NAME_DEPARTMENT VARCHAR(200) NOT NULL
);



ALTER TABLE MANAGER.EMPLOYE ADD CONSTRAINT FK_ID_DEPARTMENT
FOREIGN KEY (ID_DEPARTMENT) REFERENCES MANAGER.DEPARTMENT(ID_DEPARTMENT);